parameters:
#    ck_evt_backend.example.class: Ck\Evt\BackendBundle\Example

services:
#    ck_evt_backend.example:
#        class: %ck_evt_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
